on:
  release:
    types: [published]
name: Deploy Extension
jobs:
  Publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.20.3"
          cache: npm
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm install --unsafe-perm

      - name: Publish
        uses: lannonbr/vsce-action@master
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
        with:
          args: publish -p $VSCE_TOKEN
