on:
  release:
    types: [published]
  push:
    branches: [master]

name: Deploy Extension
jobs:
  Publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install build tools
        run: sudo apt-get install -y build-essential

      - name: Install dependencies
        run: npm install --unsafe-perm

      - name: Publish
        uses: lannonbr/vsce-action@master
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
        with:
          args: publish -p $VSCE_TOKEN
