on:
  push:
    branches: [master]

permissions:
  id-token: write
  contents: write
  pull-requests: write

env:
  skip: false

name: Deploy Extension
jobs:
  Publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install build tools
        run: sudo apt-get install -y build-essential

      - name: Install dependencies
        run: npm install --unsafe-perm

      - name: Add Git Config
        run: |
          git config user.name "Potter"
          git config user.email "aa4790139@gmail.com"
          git remote set-url origin https://x-access-token:${{ secrets.TOKEN }}@github.com/yxw007/vscode-google-translate.git

      - name: Compare tag with package.json version
        run: |
          closest_tag=$(git describe --tags --exact-match 2>/dev/null || echo "")
          echo "Closest tag: $closest_tag"
          if [ "$closest_tag" != "" ]; then
            echo "skip=true" >> $GITHUB_ENV
          else
            echo "skip=false" >> $GITHUB_ENV
          fi

      - name: Output skip
        run: |
          echo "skip: $skip"

        # skip = true means skip steps below
      - name: Generate Changelog and Create Release
        if: env.skip == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          npm run release --no-git-checks

      - uses: ad-m/github-push-action@v0.6.0
        if: env.skip == 'false'
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: master

      - name: Publish
        uses: lannonbr/vsce-action@master
        if: env.skip == 'false'
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
        with:
          args: publish -p $VSCE_TOKEN
